### ISSUE TITLE
Operation description links unreachable

### ISSUE THREAD

**Issue by jasonhemann** [alviano/asp-chef#2]
Hi! Is it possible to make the operations' descriptions persist as I move the hover over to them? 

For instance, the Meta Classical Models operation has a link in its description, but I can't seem to hover over it to click.

**Comment by alviano** [comment]
Hi Jason!

Try the (recently added) Documentation operation, or the
https://asp-chef.alviano.net/doc endpoint.
They are both preliminary, but should help with what you want to do.

m

**Comment by jasonhemann** [comment]
Oh, awesome. Thank you!
